name: ricoz_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  video_player: ^2.6.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  flutter_svg: ^1.1.6
  google_sign_in: ^6.1.2
  http: ^0.13.5
  local_auth: ^2.1.6

dev_dependencies:
  dotted_border: ^2.0.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/image 1 (3).png
    - assets/image 125 (4).png
    - assets/
    - assets/course/
    - assets/Handling/
    - assets/ads/
    - assets/service/

  fonts:
    - family: Cormorant Garamond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Bold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Bold.ttf
