// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB5P2I3zh11xs_EU6ZzFcnQp0X_rJhwKI',
    appId: '1:130911537111:web:3767c46df636e15947ed92',
    messagingSenderId: '130911537111',
    projectId: 'firstricoz-b59a2',
    authDomain: 'firstricoz-b59a2.firebaseapp.com',
    storageBucket: 'firstricoz-b59a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6XVIYICvRyWrpBfTrfeFm8Rl7Ef9ZVW0',
    appId: '1:130911537111:android:9a37a3f1d2363f3947ed92',
    messagingSenderId: '130911537111',
    projectId: 'firstricoz-b59a2',
    storageBucket: 'firstricoz-b59a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEMrcFraqcuC_Qu20r_IFm6224mzsVvro',
    appId: '1:130911537111:ios:531c3da5c4e76b7a47ed92',
    messagingSenderId: '130911537111',
    projectId: 'firstricoz-b59a2',
    storageBucket: 'firstricoz-b59a2.appspot.com',
    iosClientId: '130911537111-nie1oi0go5hnqgjgsros29agb6nkrtgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ricozApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEMrcFraqcuC_Qu20r_IFm6224mzsVvro',
    appId: '1:130911537111:ios:531c3da5c4e76b7a47ed92',
    messagingSenderId: '130911537111',
    projectId: 'firstricoz-b59a2',
    storageBucket: 'firstricoz-b59a2.appspot.com',
    iosClientId: '130911537111-nie1oi0go5hnqgjgsros29agb6nkrtgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ricozApp',
  );
}
